// Object-storage port (PV-01). Every file the product keeps -- import
// uploads, generated exports -- goes through this interface, and nothing
// outside src/providers/ knows which vendor holds the bytes.
//
// Uploads never pass through the API (PV-02): the API asks the adapter for a
// short-lived signed target, the client sends the bytes straight to it, and
// the API only ever looks at what arrived (head + one streamed read).

import type { Readable } from 'node:stream';

/**
 * Where and how the client sends the bytes.
 *
 * `PUT`: send the body as-is with exactly `headers`. `POST`: a form post of
 * `fields` followed by the file (S3 POST policy, Cloudinary-style signed
 * forms). Every adapter here returns PUT; the shape allows POST so an
 * adapter that needs it is one file, not a client change.
 */
export interface UploadTarget {
  url: string;
  method: 'PUT' | 'POST';
  headers: Record<string, string>;
  fields?: Record<string, string>;
}

export interface CreateUploadInput {
  key: string;
  contentType: string;
  /**
   * The declared size, bound into the signature. A presigned PUT can pin an
   * exact length but not a range (a range needs a POST policy, which R2 does
   * not implement), so the policy's maximum is checked before signing and the
   * provider enforces this exact value.
   */
  contentLength: number;
  /** Seconds the target stays usable. */
  expiresIn: number;
}

export interface ObjectInfo {
  size: number;
  contentType: string | null;
  etag: string | null;
}

export interface ObjectStorage {
  readonly driver: 'disk' | 'memory' | 's3';
  createUpload(input: CreateUploadInput): Promise<UploadTarget>;
  /** A short-lived GET URL; `filename` sets Content-Disposition: attachment. */
  createDownloadUrl(key: string, opts: { expiresIn: number; filename?: string }): Promise<string>;
  head(key: string): Promise<ObjectInfo | null>;
  getStream(key: string): Promise<Readable | null>;
  /** Server-generated files only (exports). Client files arrive via createUpload. */
  put(key: string, body: Buffer | string, contentType: string): Promise<void>;
  /** Deleting a missing object is not an error. */
  delete(key: string): Promise<void>;
}

/**
 * Keys are generated by the server (`uploads/<user>/<uuid>`), never taken
 * from a client, but every adapter still refuses anything that could walk
 * out of its namespace. One rule for all adapters, so a key valid on disk is
 * valid on S3.
 */
export function assertValidKey(key: string): void {
  if (
    !/^[A-Za-z0-9][A-Za-z0-9._/-]{0,511}$/.test(key) ||
    key.split('/').some((part) => part === '' || part === '.' || part === '..')
  ) {
    throw new Error(`Invalid object key: ${JSON.stringify(key)}`);
  }
}

/** Content-Disposition for a download, with a filename safe in a header. */
export function attachmentDisposition(filename: string): string {
  const ascii = filename.replace(/[^A-Za-z0-9._-]/g, '_').slice(0, 128) || 'download';
  return `attachment; filename="${ascii}"`;
}

/** Read a whole stream into memory. Callers bound the size first (head). */
export async function readAll(stream: Readable): Promise<Buffer> {
  const chunks: Buffer[] = [];
  for await (const chunk of stream) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  return Buffer.concat(chunks);
}
